version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:8081"
      - "--entrypoints.dashboard.address=:8082"
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: overlay
